[package]
name = "wplabs-lsp"
version = "0.1.6"
edition = "2021"

[[bin]]
name = "wplabs-lsp"
path = "src/main.rs"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
tree-sitter = "0.26"
tree-sitter-wfl = { git = "https://github.com/wp-labs/tree-sitter-wfl", rev = "4d4c55f519d8449f399bcaca2860570ebc8b2595" }
tree-sitter-wfs = { git = "https://github.com/wp-labs/tree-sitter-wfs", rev = "39e5fb246b7412fb43660dbb162bdb3bf9ec2404" }
tree-sitter-wpl = { git = "https://github.com/wp-labs/tree-sitter-wpl", rev = "3cc86519ff4adeb818e75b70c1c565098c1876b0" }
tree-sitter-oml = { git = "https://github.com/wp-labs/tree-sitter-oml", rev = "6105fa6360df78e2d477e9e496551875e5e93ea2" }
tree-sitter-wfg = { git = "https://github.com/wp-labs/tree-sitter-wfg", rev = "d60dcd01183611bb0f89af79c0e948ce803a65bf" }
tree-sitter-gxl = { git = "https://github.com/wp-labs/tree-sitter-gxl", rev = "85e678d9aedac0f3422ad547d668b3b8b0103b9b" }
lsp-types = "0.94"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "6"
log = "0.4"
env_logger = "0.11"
